name: test_Django
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: sudo pip install flake8
      - run: echo "::set-env name=DJANGO_SETTINGS_MODULE::contact_app.settings"
      - run: sudo python -m pip install --upgrade pip
      - run: sudo pip install -r requirements.txt # install all our dependencies for the project
      - run: pytest . # run pytest test
      - run: flake8 . # run flake8 test